minsize: 1
maxsize: 1
java_opts:
  xmx: 2G

# number of runs for the same tool/scenario/query/size
runs: 5
# number of modify-recheck iterations
iterationcount: 10
# timeout for the benchmark processes
timeout: 600
#email:
#  address: trainbenchmark@gmail.com
#  password: iliketrains
#  host: smtp.gmail.com:587
queries:
- ConnectedSegments
- PosLength
- RouteSensor
- SemaphoreNeighbor
- SwitchSensor
- SwitchSet

scenarios:
- Batch
- Inject
- Repair

tools:
#- allegro
- blazegraph
- drools5
- drools6
- emfapi
- emfincquery
#- iqdcore
- jena
- mysql
- neo4j
- sesame
#- virtuoso

# optional arguments. for example, neo4j is invoked with and without the javaapi argument as well.
generator_optional_arguments:
  rdf:
  - metamodel

benchmark_optional_arguments:
  neo4j:
  - coreapi
  jena:
  - inferencing
  sesame:
  - inferencing
  emfincquery:
  - localsearch
